#+HUGO_BASE_DIR: ../
#+HUGO_WEIGHT: auto
#+HUGO_SECTION: getting-started

* Getting Started
:PROPERTIES:
:EXPORT_HUGO_WEIGHT: 0
:EXPORT_FILE_NAME: _index
:END:
* Setup
:PROPERTIES:
:EXPORT_FILE_NAME: setup
:END:

You can download Julia at https://julialang.org/downloads/. For specific instructions, see https://julialang.org/downloads/platform/.

Once installed, open a command line, type =julia=, and press enter. You should see something similar to the following output:

#+BEGIN_EXPORT html
<pre class="julia-repl"><font color="#C678DD">$</font> <font color="#98C379">julia</font>
               <font color="#98C379"><b>_</b></font>
   <font color="#61AFEF"><b>_</b></font>       _ <font color="#E06C75"><b>_</b></font><font color="#98C379"><b>(_)</b></font><font color="#C678DD"><b>_</b></font>     |  Documentation: https://docs.julialang.org
  <font color="#61AFEF"><b>(_)</b></font>     | <font color="#E06C75"><b>(_)</b></font> <font color="#C678DD"><b>(_)</b></font>    |
   _ _   _| |_  __ _   |  Type &quot;?&quot; for help, &quot;]?&quot; for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__&apos;_|_|_|\__&apos;_|  |  Official https://julialang.org/ release
|__/                   |

<font color="#98C379"><b>julia&gt; </b></font>
</pre>
#+END_EXPORT

To exit the program, press ~CTRL-d~ or type ~exit()~ and press enter.

* Julia Intro
:PROPERTIES:
:EXPORT_FILE_NAME: julia-intro
:END:
** Programming

Computers only understand ones and zeros. When a computer runs a program, it's really reading something like this:

#+begin_src text
01111111 01000101 01001100 01000110
00000010 00000001 00000001 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
#+end_src

Computers understand this just fine. Humans, on the other hand, have a difficult time writing and understanding instructions like these.

In order to make writing this easier, /programming languages/ were invented. Humans write code in a programming language, and that code is translated into ones and zeros that the computer can run.

Some programming languages involve giving bare-bones commands to the computer. Text written in these languages usually gets translated to a similar amount of ones and zeros. These are generally called /low level langauges/. The opposite of low level languages are /high level langauges/, where one simple command can translate to tons of ones and zeros.

Low level languages are useful for pushing a computer to its limits, but they are generally harder to write. High level languages allow humans to quickly write and understand code without having to worry about the low level details. Using a high level language is like ordering food at a restaurant whereas a low level language is like cooking a dish from scratch.

Consider a program that simply prints "Hello World" to the screen. Here is what that program would look like in various languages, roughly from low to high level.

*** x86-64 Assembly (Linux)

#+begin_src asm
global _start

section .text

_start:
  mov rax, 1
  mov rdi, 1
  mov rsi, msg
  mov rdx, msglen
  syscall

  mov rax, 60
  mov rdi, 0
  syscall

section .rodata
  msg: db "Hello, World!", 10
  msglen: equ $ - msg
#+end_src

*** C

#+begin_src c
#include <stdio.h>

int main(void) {
    printf("Hello, World!\n");
    return 0;
}

#+end_src

*** Java

#+begin_src java
class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
#+end_src

*** Julia

#+begin_src julia
println("Hello, World!")
#+end_src

*** Python

#+begin_src python
print("Hello, World!")
#+end_src

*** Lisp

#+begin_src lisp
(print "Hello, World!")
#+end_src

** The Julia Language

Julia is a relatively new programming language. Version 1.0 was released in August of 2018. It was designed with computational scientists in mind, but it is a general purpose language too.

Like most other languages, Julia code is executed from the top down. For example, the following code prints "ready", "set", and "go" in that order.

#+begin_src julia
println("ready")
println("set")
println("go")
#+end_src

* REPL Intro
:PROPERTIES:
:EXPORT_FILE_NAME: repl-intro
:END:

When you type =julia= in the command line, you should get an output like this:

#+BEGIN_EXPORT html
<pre class="julia-repl"><font color="#C678DD">$</font> <font color="#98C379">julia</font>
               <font color="#98C379"><b>_</b></font>
   <font color="#61AFEF"><b>_</b></font>       _ <font color="#E06C75"><b>_</b></font><font color="#98C379"><b>(_)</b></font><font color="#C678DD"><b>_</b></font>     |  Documentation: https://docs.julialang.org
  <font color="#61AFEF"><b>(_)</b></font>     | <font color="#E06C75"><b>(_)</b></font> <font color="#C678DD"><b>(_)</b></font>    |
   _ _   _| |_  __ _   |  Type &quot;?&quot; for help, &quot;]?&quot; for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__&apos;_|_|_|\__&apos;_|  |  Official https://julialang.org/ release
|__/                   |

<font color="#98C379"><b>julia&gt; </b></font>
</pre>
#+END_EXPORT

This is called the Julia REPL (short for read-eval-print-loop). The REPL allows you to write code interactively instead of saving it in a file. In its most basic form, the REPL acts like a calculator. Type an expression like ~2 + 2~ and press enter. You should see the result on the next line:

#+BEGIN_EXPORT html
<pre class="julia-repl"><font color="#98C379"><b>julia&gt; </b></font>2 + 2
4

<font color="#98C379"><b>julia&gt; </b></font>7 * 8
56
</pre>
#+END_EXPORT

To exit the REPL, press ~CTRL-d~ or type ~exit()~ and press enter.
